sudo: false

language:
  - php
  - node_js

before_script:
  - curl -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar

script:
  - echo "Deploy only"

before_deploy:
  - export RELEASE_FOLDER=mins
  - php /tmp/wp-cli.phar package install runcommand/dist-archive
  - cp -rv ${TRAVIS_BUILD_DIR} /tmp/${RELEASE_FOLDER}
  - mv /tmp/${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}
  - php /tmp/wp-cli.phar dist-archive ${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}/${RELEASE_FOLDER}.zip --format=zip --debug

deploy:
  provider: releases
  api_key:
    secure: Z2l67GM6bYZc0We0eyk3OHxumgfNsFq1+4gVUe1HL0C3ZJm60LPOjCK0jeHeZ+bT3W6lLQcwX1DMOOSwLdhrDR8PAogo1B4e7Jc4uNgTbAIfhPkqIA5rEb6v/nJV4+IcNr+YvUhtBjt9NP3M4uq8VcMuyqShVl+uqi1unBToIt1kaGPqHeULF5AtmVkYx/BImMGZNSjSKDVxFeCbpqS1hrj+DZDtpgAIkS4jIOPN+wzVYHXYZrLd5XraexTdh9ye0Az4NLwf2GfZZKgIJF1bg7n3E0DLKBwR/7fw8RjpVmkxKx9lpSI5ZhutWbNlot3J9gbO9tcdP8jUlNtae5ayTMcXIXMh33yQ/H2j4HHR14Uy70SvMYtsqIHWStcyEhklj0xp7Ycqat8xtdB+lq6ZyxRKXmwG1mG4aHCjoRPvIw8Urfe4ODoKcvwD9firWONpuLq/SfgFT0dpkRDnnzD+1hrqNqO+/O/hMDeqySUCckMzTv+LJAThaV4IgfDxj0JeH+JoxqkiKVAVIAru+6Iep2FPJS44QYipAryINqy6KCMc9TbGcQD02tbReb10RJNLprgVwUsxozqPh8YTIRW6quOmhJFEEn/uynsF/UTr6eWHflOIyXwyPSRUTH9Fudd/NGVmbZZltRo4jnv6dqocJmOf4TfxBXSjlFw7gDwyIJQ=
  file: mins.zip
  on:
    tags: true
    repo: godaddy/wp-mins-theme
  skip_cleanup: true
  overwrite: true
